# Generated by Django 3.1 on 2020-10-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MdlEnrolFlatfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=30)),
                ('roleid', models.BigIntegerField()),
                ('userid', models.CharField(max_length=100)),
                ('courseid', models.BigIntegerField()),
                ('grade', models.CharField(blank=True, max_length=45, null=True)),
                ('timestart', models.BigIntegerField()),
                ('timeend', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_enrol_flatfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('q_c_id', models.IntegerField()),
                ('q_s_id', models.IntegerField()),
                ('q_c_name', models.CharField(max_length=100)),
                ('ch_id', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('satisfaction', models.CharField(blank=True, max_length=10, null=True)),
                ('t_year', models.CharField(max_length=45)),
                ('t_semester', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
    ]
