# Generated by Django 3.1 on 2020-10-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MdlEnrolFlatfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=30)),
                ('roleid', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('courseid', models.BigIntegerField()),
                ('coursename', models.CharField(blank=True, max_length=100, null=True)),
                ('grade', models.BigIntegerField(blank=True, null=True)),
                ('timestart', models.BigIntegerField()),
                ('timeend', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_enrol_flatfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MdlRoleAssignments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('roleid', models.BigIntegerField()),
                ('contextid', models.BigIntegerField()),
                ('userid', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
                ('modifierid', models.BigIntegerField()),
                ('component', models.CharField(max_length=100)),
                ('itemid', models.BigIntegerField()),
                ('sortorder', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_role_assignments',
                'managed': False,
            },
        ),
    ]
