# Generated by Django 3.1 on 2020-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningLevel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdlEnrolFlatfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=30)),
                ('roleid', models.BigIntegerField()),
                ('userid', models.CharField(max_length=100)),
                ('courseid', models.BigIntegerField()),
                ('grade', models.CharField(blank=True, max_length=45, null=True)),
                ('timestart', models.BigIntegerField()),
                ('timeend', models.BigIntegerField()),
                ('timemodified', models.BigIntegerField()),
            ],
            options={
                'db_table': 'mdl_enrol_flatfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
            ],
        ),
    ]
